
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 9999, host: 8080 # ici changer les port de l'host
  config.vm.network "public_network",
  use_dhcp_assigned_default_route: true
  config.vm.hostname = "reverse-shell"
  config.ssh.forward_agent = true
  config.ssh.insert_key=false

  config.vm.provision "init",type: "shell",  inline: <<-SHELL
    echo ============================== Start SHELL ==============================
    sudo yum update -y
    sudo yum install -y epel-release 
    sudo yum install -y python3
    sudo yum install -y python-pip
    sudo yum install -y git
    pip install --upgrade pip
    sudo pip install termcolor
    sudo pip3 install termcolor
    echo ============================== Install OK ==============================
    sudo git clone https://github.com/Saluc00/UF-Infra-B2.git
    echo ============================== CLone OK ==============================
  SHELL
end
