
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.network :public_network, :bridge => "eth1", :auto_config => false
  config.vm.hostname = "reverse-shell"
  config.vm.network :private_network, ip: "192.168.0.10"

  config.vm.provision "init",type: "shell",  inline: <<-SHELL
    sudo yum update
    sudo yum install -y python3
    sudo yum install -y git
    cd /home/vagrant
    git clone https://github.com/Saluc00/UF-Infra-B2.git
    cd /
  SHELL
end
