
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.network :public_network, :bridge => "eth1", :auto_config => false
  config.vm.hostname = "reverse-shell"
  config.vm.network :private_network, ip: "192.168.0.10"
  config.ssh.forward_agent = true
  config.ssh.insert_key=false

  config.vm.provision "init",type: "shell",  inline: <<-SHELL
    echo ============================== Start SHELL ==============================
    sudo yum update -y
    sudo yum install -y epel-release 
    sudo yum install -y python3
    sudo yum install -y python-pip
    sudo yum install -y git
    pip install --upgrade pip
    sudo pip install termcolor
    sudo pip3 install termcolor
    echo ============================== Install OK ==============================
    sudo git clone https://github.com/Saluc00/UF-Infra-B2.git
    echo ============================== Install OK ==============================
    echo Ip PUBLIC ===
    ip -f inet a show eth0 | grep inet | awk '{ print $2}'
    echo Ip LOCAL ===
    ip -f inet a show eth2 | grep inet | awk '{ print $2}'
    echo ============================== CLone OK ==============================
  SHELL
end